# Translations template for nova.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the nova project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: nova\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-04-06 06:16+0000\n"
"PO-Revision-Date: 2015-04-03 18:00+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Korean (Korea) (http://www.transifex.com/projects/p/nova/"
"language/ko_KR/)\n"
"Language: ko_KR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: nova/filters.py:80
#, python-format
msgid "Filter %s returned 0 hosts"
msgstr ""

#: nova/service.py:161
#, python-format
msgid "Starting %(topic)s node (version %(version)s)"
msgstr "%(topic)s 노드(버전 %(version)s) 시작 중"

#: nova/wsgi.py:149
#, python-format
msgid "%(name)s listening on %(host)s:%(port)s"
msgstr "%(name)s이(가) %(host)s:%(port)s에서 청취 중임"

#: nova/wsgi.py:253
msgid "Stopping WSGI server."
msgstr "WSGI 서버를 중지 중입니다. "

#: nova/wsgi.py:273
msgid "WSGI server has stopped."
msgstr "WSGI 서버가 중지되었습니다. "

#: nova/api/ec2/__init__.py:465
#, python-format
msgid ""
"Unauthorized request for controller=%(controller)s and action=%(action)s"
msgstr "controller=%(controller)s 및 action=%(action)s에 대한 권한 없는 요청"

#: nova/api/ec2/cloud.py:415
#, python-format
msgid "Create snapshot of volume %s"
msgstr "%s 볼륨의 스냅샷 작성"

#: nova/api/ec2/cloud.py:458
#, python-format
msgid "Create key pair %s"
msgstr "%s 키 쌍 작성"

#: nova/api/ec2/cloud.py:470
#, python-format
msgid "Import key %s"
msgstr "%s 키 가져오기"

#: nova/api/ec2/cloud.py:483
#, python-format
msgid "Delete key pair %s"
msgstr "%s 키 쌍 삭제"

#: nova/api/ec2/cloud.py:786
#, python-format
msgid "Get console output for instance %s"
msgstr "%s 인스턴스에 대한 콘솔 출력 가져오십시오. "

#: nova/api/ec2/cloud.py:859
#, python-format
msgid "Create volume from snapshot %s"
msgstr "%s 스냅샷에서 볼륨 작성"

#: nova/api/ec2/cloud.py:863 nova/api/openstack/compute/contrib/volumes.py:163
#, python-format
msgid "Create volume of %s GB"
msgstr "%s GB의 볼륨 작성"

#: nova/api/ec2/cloud.py:903
#, python-format
msgid "Attach volume %(volume_id)s to instance %(instance_id)s at %(device)s"
msgstr "%(volume_id)s 볼륨을 %(device)s에 있는 %(instance_id)s 인스턴스에 첨부"

#: nova/api/ec2/cloud.py:933 nova/api/openstack/compute/contrib/volumes.py:392
#, python-format
msgid "Detach volume %s"
msgstr "%s 볼륨 분리"

#: nova/api/ec2/cloud.py:1300
msgid "Allocate address"
msgstr "주소 할당"

#: nova/api/ec2/cloud.py:1305
#, python-format
msgid "Release address %s"
msgstr "주소 릴리즈 %s"

#: nova/api/ec2/cloud.py:1310
#, python-format
msgid "Associate address %(public_ip)s to instance %(instance_id)s"
msgstr "%(public_ip)s 주소를 %(instance_id)s 인스턴스에 연관"

#: nova/api/ec2/cloud.py:1343
#, python-format
msgid "Disassociate address %s"
msgstr "%s 주소 연관 해제"

#: nova/api/ec2/cloud.py:1496
#, python-format
msgid "Reboot instance %r"
msgstr "%r 인스턴스 다시 부팅"

#: nova/api/ec2/cloud.py:1611
#, python-format
msgid "De-registering image %s"
msgstr "%s 이미지 등록 취소"

#: nova/api/ec2/cloud.py:1647
#, python-format
msgid "Registered image %(image_location)s with id %(image_id)s"
msgstr "ID가 %(image_id)s인 %(image_location)s 이미지를 등록했음"

#: nova/api/ec2/cloud.py:1716
#, python-format
msgid "Updating image %s publicity"
msgstr "이미지 %s 공개 업데이트"

#: nova/api/ec2/ec2utils.py:292
msgid "Timestamp is invalid."
msgstr "시간소인이 올바르지 않습니다. "

#: nova/api/openstack/__init__.py:102
#, python-format
msgid "%(url)s returned with HTTP %(status)d"
msgstr "%(url)s이(가) HTTP %(status)d(으)로 리턴되었음"

#: nova/api/openstack/__init__.py:291
msgid "V3 API has been disabled by configuration"
msgstr ""

#: nova/api/openstack/__init__.py:336
#, python-format
msgid "Loaded extensions: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:522
#, python-format
msgid "Fault thrown: %s"
msgstr "처리된 결함: %s"

#: nova/api/openstack/wsgi.py:525
#, python-format
msgid "HTTP exception thrown: %s"
msgstr "HTTP 예외 처리: %s"

#: nova/api/openstack/compute/contrib/assisted_volume_snapshots.py:53
#: nova/api/openstack/compute/plugins/v3/assisted_volume_snapshots.py:56
#, python-format
msgid "Create assisted snapshot from volume %s"
msgstr ""

#: nova/api/openstack/compute/contrib/assisted_volume_snapshots.py:64
#: nova/api/openstack/compute/contrib/volumes.py:501
#: nova/api/openstack/compute/plugins/v3/assisted_volume_snapshots.py:72
#, python-format
msgid "Delete snapshot with id: %s"
msgstr "ID가 %s인 스냅샷 삭제"

#: nova/api/openstack/compute/contrib/attach_interfaces.py:120
msgid "Attach interface"
msgstr "인터페이스 첨부"

#: nova/api/openstack/compute/contrib/attach_interfaces.py:154
#, python-format
msgid "Detach interface %s"
msgstr "%s 인터페이스와 분리"

#: nova/api/openstack/compute/contrib/hosts.py:152
#: nova/api/openstack/compute/plugins/v3/hosts.py:134
#, python-format
msgid "Putting host %(host_name)s in maintenance mode %(mode)s."
msgstr "%(host_name)s 호스트를 유지보수 모드 %(mode)s에 넣습니다. "

#: nova/api/openstack/compute/contrib/hosts.py:175
#: nova/api/openstack/compute/plugins/v3/hosts.py:156
#, python-format
msgid "Enabling host %s."
msgstr "%s 호스트 사용."

#: nova/api/openstack/compute/contrib/hosts.py:177
#: nova/api/openstack/compute/plugins/v3/hosts.py:158
#, python-format
msgid "Disabling host %s."
msgstr "%s 호스트 사용 안함."

#: nova/api/openstack/compute/contrib/server_external_events.py:97
#: nova/api/openstack/compute/plugins/v3/server_external_events.py:86
#, python-format
msgid "Creating event %(name)s:%(tag)s for instance %(instance_uuid)s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:77
#, python-format
msgid "vol=%s"
msgstr "vol=%s"

#: nova/api/openstack/compute/contrib/volumes.py:111
#, python-format
msgid "Delete volume with id: %s"
msgstr "ID가 %s인 볼륨 삭제"

#: nova/api/openstack/compute/contrib/volumes.py:295
#, python-format
msgid "Attach volume %(volume_id)s to instance %(server_id)s at %(device)s"
msgstr "%(volume_id)s 볼륨을 %(device)s의 %(server_id)s 인스턴스에 첨부"

#: nova/api/openstack/compute/contrib/volumes.py:539
#, python-format
msgid "Create snapshot from volume %s"
msgstr "%s 볼륨에서 스냅샷 작성"

#: nova/cells/messaging.py:1136
#, python-format
msgid ""
"Forcing a sync of instances, project_id=%(projid_str)s, updated_since="
"%(since_str)s"
msgstr ""
"인스턴스의 동기화 강제 실행, project_id=%(projid_str)s, updated_since="
"%(since_str)s"

#: nova/cells/scheduler.py:239
#, python-format
msgid ""
"No cells available when scheduling.  Will retry in %(sleep_time)s second(s)"
msgstr ""
"스케줄 작성 시 셀을 사용할 수 없습니다. %(sleep_time)s초 후에 재시도합니다."

#: nova/cells/filters/target_cell.py:59
#, python-format
msgid ""
"Forcing direct route to %(cell_name)s because of 'target_cell' scheduler hint"
msgstr ""

#: nova/compute/api.py:1508
msgid "instance termination disabled"
msgstr "인스턴스 종료 사용 안함"

#: nova/compute/api.py:1521
#, python-format
msgid "Working on deleting snapshot %s from shelved instance..."
msgstr ""

#: nova/compute/api.py:1591
msgid "Instance is already in deleting state, ignoring this request"
msgstr ""

#: nova/compute/api.py:1636
#, python-format
msgid ""
"Found an unconfirmed migration during delete, id: %(id)s, status: %(status)s"
msgstr ""

#: nova/compute/api.py:1646
msgid "Instance may have been confirmed during delete"
msgstr ""

#: nova/compute/api.py:1663
#, python-format
msgid "Migration %s may have been confirmed during delete"
msgstr ""

#: nova/compute/api.py:1719
msgid ""
"instance is in SHELVED_OFFLOADED state, cleanup the instance's info from "
"database."
msgstr ""

#: nova/compute/api.py:2218
#, python-format
msgid "Skipping quiescing instance: %(reason)s."
msgstr ""

#: nova/compute/api.py:3879
#, python-format
msgid "Create Security Group %s"
msgstr "%s 보안 그룹 작성"

#: nova/compute/api.py:3984
#, python-format
msgid "Delete security group %s"
msgstr "%s 보안 그룹 삭제"

#: nova/compute/claims.py:167
msgid "Claim successful"
msgstr "청구 성공"

#: nova/compute/claims.py:236
#, python-format
msgid "Total %(type)s: %(total)d %(unit)s, used: %(used).02f %(unit)s"
msgstr ""

#: nova/compute/claims.py:243
#, python-format
msgid "%(type)s limit not specified, defaulting to unlimited"
msgstr ""

#: nova/compute/claims.py:250
#, python-format
msgid "%(type)s limit: %(limit).02f %(unit)s, free: %(free).02f %(unit)s"
msgstr ""

#: nova/compute/manager.py:301
#, python-format
msgid "Task possibly preempted: %s"
msgstr ""

#: nova/compute/manager.py:791
#, python-format
msgid ""
"Deleting instance as its host (%(instance_host)s) is not equal to our host "
"(%(our_host)s)."
msgstr ""
"호스트 자격의 인스턴스(%(instance_host)s) 삭제가 해당 호스트 (%(our_host)s)과"
"(와) 같지 않습니다."

#: nova/compute/manager.py:806
msgid ""
"Instance has been marked deleted already, removing it from the hypervisor."
msgstr ""

#: nova/compute/manager.py:974
msgid ""
"Service started deleting the instance during the previous run, but did not "
"finish. Restarting the deletion now."
msgstr ""

#: nova/compute/manager.py:1099
msgid "Instance found in migrating state during startup. Resetting task_state"
msgstr ""
"시작 중에 마이그레이션 상태의 인스턴스를 찾았습니다. task_state를 재설정하는 "
"중"

#: nova/compute/manager.py:1121
msgid "Rebooting instance after nova-compute restart."
msgstr "nova-compute 다시 시작 후에 인스턴스 다시 부팅 중입니다. "

#: nova/compute/manager.py:1171
#, python-format
msgid "VM %(state)s (Lifecycle Event)"
msgstr ""

#: nova/compute/manager.py:1698 nova/compute/manager.py:2149
msgid "Starting instance..."
msgstr "인스턴스 시작 중..."

#: nova/compute/manager.py:2520
#, python-format
msgid "%(action_str)s instance"
msgstr "%(action_str)s 인스턴스"

#: nova/compute/manager.py:2686
msgid "Instance disappeared during terminate"
msgstr ""

#: nova/compute/manager.py:2730
msgid "Instance is already powered off in the hypervisor when stop is called."
msgstr ""

#: nova/compute/manager.py:2893
msgid "Rebuilding instance"
msgstr "인스턴스 다시 빌드 중"

#: nova/compute/manager.py:2910
msgid "disk on shared storage, recreating using existing disk"
msgstr "공유 스토리지의 디스크, 기존 디스크를 사용하여 재작성 중"

#: nova/compute/manager.py:2914
#, python-format
msgid "disk not on shared storage, rebuilding from: '%s'"
msgstr ""

#: nova/compute/manager.py:3000
#, python-format
msgid "bringing vm to original state: '%s'"
msgstr "VM을 원래 상태로 만드는 중: '%s'"

#: nova/compute/manager.py:3031
#, python-format
msgid "Detaching from volume api: %s"
msgstr "볼륨 api에서 분리 중: %s"

#: nova/compute/manager.py:3058
msgid "Rebooting instance"
msgstr "인스턴스 재부팅 중"

#: nova/compute/manager.py:3196
msgid "instance snapshotting"
msgstr "인스턴스 스냅샷 작성 중"

#: nova/compute/manager.py:3333
msgid "Root password set"
msgstr "루트 비밀번호 설정"

#: nova/compute/manager.py:3381
#, python-format
msgid "injecting file to %s"
msgstr ""

#: nova/compute/manager.py:3419
msgid "Rescuing"
msgstr "구조 중"

#: nova/compute/manager.py:3468
msgid "Unrescuing"
msgstr "비구조 중"

#: nova/compute/manager.py:3546
#, python-format
msgid "Migration %s is already confirmed"
msgstr ""

#: nova/compute/manager.py:3567
msgid "Instance is not found during confirmation"
msgstr ""

#: nova/compute/manager.py:3755
#, python-format
msgid "Updating instance to original state: '%s'"
msgstr ""

#: nova/compute/manager.py:3802
msgid "Migrating"
msgstr "이전중"

#: nova/compute/manager.py:4145
msgid "Pausing"
msgstr "일시정지 중"

#: nova/compute/manager.py:4161
msgid "Unpausing"
msgstr "일시정지 해제 중"

#: nova/compute/manager.py:4199 nova/compute/manager.py:4216
msgid "Retrieving diagnostics"
msgstr "진단 검색 중"

#: nova/compute/manager.py:4255
msgid "Resuming"
msgstr "재개 중"

#: nova/compute/manager.py:4486
msgid "Get console output"
msgstr "콘솔 출력 가져오기"

#: nova/compute/manager.py:4731
#, python-format
msgid "Attaching volume %(volume_id)s to %(mountpoint)s"
msgstr "%(volume_id)s 볼륨을 %(mountpoint)s에 첨부 중"

#: nova/compute/manager.py:4756
#, python-format
msgid "Detach volume %(volume_id)s from mountpoint %(mp)s"
msgstr "%(mp)s 마운트 지점에서 %(volume_id)s 볼륨 분리"

#: nova/compute/manager.py:5248
msgid "_post_live_migration() is started.."
msgstr "_post_live_migration()이 시작됩니다. "

#: nova/compute/manager.py:5329
#, python-format
msgid "Migrating instance to %s finished successfully."
msgstr ""

#: nova/compute/manager.py:5331
msgid ""
"You may see the error \"libvirt: QEMU error: Domain not found: no domain "
"with matching name.\" This error can be safely ignored."
msgstr ""
"오류 \"libvirt: QEMU 오류: 도메인을 찾을 수 없음: 일치하는 이름의 도메인이 없"
"음.\" 이 오류는 무시해도 무방합니다."

#: nova/compute/manager.py:5356
msgid "Post operation of migration started"
msgstr "마이그레이션의 사후 오퍼레이션이 시작했음"

#: nova/compute/manager.py:5620
#, python-format
msgid ""
"Found %(migration_count)d unconfirmed migrations older than "
"%(confirm_window)d seconds"
msgstr ""
"%(confirm_window)d초 이상 미확정 상태인 %(migration_count)d개의 마이그레이션 "
"발견함"

#: nova/compute/manager.py:5635
#, python-format
msgid ""
"Automatically confirming migration %(migration_id)s for instance "
"%(instance_uuid)s"
msgstr ""
"%(instance_uuid)s 인스턴스에 대한 %(migration_id)s 마이그레이션을 자동으로 확"
"인 중"

#: nova/compute/manager.py:5689
#, python-format
msgid "Error auto-confirming resize: %s. Will retry later."
msgstr ""

#: nova/compute/manager.py:5737
#, python-format
msgid ""
"Running instance usage audit for host %(host)s from %(begin_time)s to "
"%(end_time)s. %(number_instances)s instances."
msgstr ""
"%(begin_time)s에서 %(end_time)s. %(number_instances)s 인스턴스까지 %(host)s "
"호스트에 대한 인스턴스 사용 감사를 실행하는 중입니다. "

#: nova/compute/manager.py:5785
msgid "Updating bandwidth usage cache"
msgstr "대역폭 사용 캐시 업데이트"

#: nova/compute/manager.py:5966 nova/compute/manager.py:6023
#, python-format
msgid ""
"During sync_power_state the instance has a pending task (%(task)s). Skip."
msgstr ""

#: nova/compute/manager.py:6010
#, python-format
msgid ""
"During the sync_power process the instance has moved from host %(src)s to "
"host %(dst)s"
msgstr ""
"sync_power 프로세스 중에 %(src)s 호스트에서 %(dst)s 호스트로 인스턴스가 이동"
"되었습니다."

#: nova/compute/manager.py:6031
#, python-format
msgid ""
"During _sync_instance_power_state the DB power_state (%(db_power_state)s) "
"does not match the vm_power_state from the hypervisor (%(vm_power_state)s). "
"Updating power_state in the DB to match the hypervisor."
msgstr ""

#: nova/compute/manager.py:6178
msgid "Reclaiming deleted instance"
msgstr "재확보가 인스턴스를 삭제했음"

#: nova/compute/manager.py:6208
#, python-format
msgid "Deleting orphan compute node %s"
msgstr ""

#: nova/compute/manager.py:6260
#, python-format
msgid ""
"Powering off instance with name label '%s' which is marked as DELETED but "
"still present on host."
msgstr ""

#: nova/compute/manager.py:6278
#, python-format
msgid ""
"Destroying instance with name label '%s' which is marked as DELETED but "
"still present on host."
msgstr ""

#: nova/compute/manager.py:6326
#, python-format
msgid "Setting instance back to %(state)s after: %(error)s"
msgstr ""

#: nova/compute/manager.py:6336
#, python-format
msgid "Setting instance back to ACTIVE after: %s"
msgstr ""

#: nova/compute/resource_tracker.py:341
#, python-format
msgid "Compute_service record created for %(host)s:%(node)s"
msgstr "Compute_service 레코드가 %(host)s:%(node)s에 대해 작성됨"

#: nova/compute/resource_tracker.py:373
#, python-format
msgid "Auditing locally available compute resources for node %(node)s"
msgstr ""

#: nova/compute/resource_tracker.py:380
msgid ""
"Virt driver does not support 'get_available_resource'. Compute tracking is "
"disabled."
msgstr ""

#: nova/compute/resource_tracker.py:477
#, python-format
msgid "Compute_service record updated for %(host)s:%(node)s"
msgstr "Compute_service 레코드가 %(host)s:%(node)s에 대해 업데이트됨"

#: nova/compute/resource_tracker.py:552
#, python-format
msgid "Total usable vcpus: %(tcpu)s, total allocated vcpus: %(ucpu)s"
msgstr ""

#: nova/compute/resource_tracker.py:559
#, python-format
msgid ""
"Final resource view: name=%(node)s phys_ram=%(phys_ram)sMB used_ram="
"%(used_ram)sMB phys_disk=%(phys_disk)sGB used_disk=%(used_disk)sGB "
"total_vcpus=%(total_vcpus)s used_vcpus=%(used_vcpus)s pci_stats=%(pci_stats)s"
msgstr ""

#: nova/compute/resource_tracker.py:641
#, python-format
msgid "Updating from migration %s"
msgstr "%s 마이그레이션에서 업데이트 중"

#: nova/conductor/api.py:294
msgid "nova-conductor connection established successfully"
msgstr ""

#: nova/consoleauth/manager.py:98
#, python-format
msgid "Received Token: %(token)s, %(token_dict)s"
msgstr ""

#: nova/consoleauth/manager.py:123
#, python-format
msgid "Checking Token: %(token)s, %(token_valid)s"
msgstr ""

#: nova/db/sqlalchemy/api.py:3422
#, python-format
msgid ""
"quota_usages out of sync, updating. project_id: %(project_id)s, user_id: "
"%(user_id)s, resource: %(res)s, tracked usage: %(tracked_use)s, actual "
"usage: %(in_use)s"
msgstr ""

#: nova/db/sqlalchemy/api.py:5234
#, python-format
msgid ""
"Volume(%s) has lower stats then what is in the database. Instance must have "
"been rebooted or crashed. Updating totals."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/234_add_expire_reservations_index.py:36
#: nova/db/sqlalchemy/migrate_repo/versions/248_add_expire_reservations_index.py:36
msgid ""
"Skipped adding reservations_deleted_expire_idx because an equivalent index "
"already exists."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/234_add_expire_reservations_index.py:58
#: nova/db/sqlalchemy/migrate_repo/versions/248_add_expire_reservations_index.py:58
msgid ""
"Skipped removing reservations_deleted_expire_idx because index does not "
"exist."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/274_update_instances_project_id_index.py:36
msgid ""
"Skipped adding instances_project_id_deleted_idx because an equivalent index "
"already exists."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/274_update_instances_project_id_index.py:58
msgid ""
"Skipped adding instances_project_id_idx because an equivalent index already "
"exists."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/277_add_fixed_ip_updated_index.py:40
#, python-format
msgid "Skipped adding %s because an equivalent index already exists."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/277_add_fixed_ip_updated_index.py:51
#, python-format
msgid "Skipped removing %s because no such index exists"
msgstr ""

#: nova/image/s3.py:385
#, python-format
msgid "Image %s was deleted underneath us"
msgstr ""

#: nova/image/download/file.py:163
#, python-format
msgid "Copied %(source_file)s using %(module_str)s"
msgstr ""

#: nova/network/api.py:225 nova/network/neutronv2/api.py:1103
#, python-format
msgid "re-assign floating IP %(address)s from instance %(instance_id)s"
msgstr "%(instance_id)s에서 부동 IP %(address)s 재지정"

#: nova/network/driver.py:42
#, python-format
msgid "Loading network driver '%s'"
msgstr "네트워크 드라이버 '%s' 로드 중"

#: nova/network/floating_ips.py:176
#, python-format
msgid "Floating IP %s is not associated. Ignore."
msgstr ""

#: nova/network/floating_ips.py:549
#, python-format
msgid "Starting migration network for instance %s"
msgstr ""

#: nova/network/floating_ips.py:585
#, python-format
msgid "Finishing migration network for instance %s"
msgstr ""

#: nova/network/manager.py:335
#, python-format
msgid "Configured network %(network)s on host %(host)s"
msgstr ""

#: nova/network/manager.py:508
#, python-format
msgid "Allocated network: '%s' for instance"
msgstr ""

#: nova/network/manager.py:571
#, python-format
msgid "Network deallocated for instance (fixed ips: '%s')"
msgstr ""

#: nova/network/minidns.py:201
#, python-format
msgid "deleted %s"
msgstr ""

#: nova/network/neutronv2/api.py:1575
#, python-format
msgid ""
"Port %s from network info_cache is no longer associated with instance in "
"Neutron. Removing from network info_cache."
msgstr ""

#: nova/network/security_group/neutron_driver.py:449
#: nova/network/security_group/neutron_driver.py:504
#, python-format
msgid "Adding security group %(security_group_id)s to port %(port_id)s"
msgstr "보안 그룹 %(security_group_id)s을(를) %(port_id)s 포트에 추가 중"

#: nova/openstack/common/eventlet_backdoor.py:146
#, python-format
msgid "Eventlet backdoor listening on %(port)s for process %(pid)d"
msgstr "Eventlet 백도어는 프로세스 %(pid)d 일 동안 %(port)s에서 수신"

#: nova/openstack/common/periodic_task.py:120
#, python-format
msgid "Skipping periodic task %(task)s because its interval is negative"
msgstr "간격이 음수이기 때문에 주기적 태스크 %(task)s을(를) 건너뜀"

#: nova/openstack/common/periodic_task.py:125
#, python-format
msgid "Skipping periodic task %(task)s because it is disabled"
msgstr "사용 안하기 때문에 주기적 태스크 %(task)s을(를) 건너뜀"

#: nova/openstack/common/service.py:173
#, python-format
msgid "Caught %s, exiting"
msgstr "%s 발견, 종료 중"

#: nova/openstack/common/service.py:235
msgid "Parent process has died unexpectedly, exiting"
msgstr "상위 프로세스가 예기치 않게 정지했습니다. 종료 중"

#: nova/openstack/common/service.py:266
#, python-format
msgid "Child caught %s, exiting"
msgstr "자식으로 된 %s가 존재함."

#: nova/openstack/common/service.py:305
msgid "Forking too fast, sleeping"
msgstr "포크가 너무 빠름. 정지 중"

#: nova/openstack/common/service.py:324
#, python-format
msgid "Started child %d"
msgstr "%d 하위를 시작했음"

#: nova/openstack/common/service.py:334
#, python-format
msgid "Starting %d workers"
msgstr "%d 작업자 시작 중"

#: nova/openstack/common/service.py:351
#, python-format
msgid "Child %(pid)d killed by signal %(sig)d"
msgstr "%(pid)d 하위가 %(sig)d 신호에 의해 강제 종료됨"

#: nova/openstack/common/service.py:355
#, python-format
msgid "Child %(pid)s exited with status %(code)d"
msgstr "%(pid)s 하위가 %(code)d 상태와 함께 종료했음"

#: nova/openstack/common/service.py:390
#, python-format
msgid "Caught %s, stopping children"
msgstr "%s 발견, 하위 중지 중"

#: nova/openstack/common/service.py:405
msgid "Wait called after thread killed. Cleaning up."
msgstr ""

#: nova/openstack/common/service.py:421
#, python-format
msgid "Waiting on %d children to exit"
msgstr "%d 하위에서 종료하기를 대기 중임"

#: nova/scheduler/host_manager.py:563
#, python-format
msgid "Removing dead compute node %(host)s:%(node)s from scheduler"
msgstr ""
"스케줄러에서 사용하지 않는 계산 노드 %(host)s:%(node)s을(를) 제거하는 중"

#: nova/scheduler/host_manager.py:625
#, python-format
msgid ""
"Received an update from an unknown host '%s'. Re-created its InstanceList."
msgstr ""

#: nova/scheduler/host_manager.py:643
#, python-format
msgid ""
"Received a delete update from an unknown host '%s'. Re-created its "
"InstanceList."
msgstr ""

#: nova/scheduler/host_manager.py:661
#, python-format
msgid ""
"The instance sync for host '%s' did not match. Re-created its InstanceList."
msgstr ""

#: nova/scheduler/host_manager.py:665
#, python-format
msgid "Successfully synced instances from host '%s'."
msgstr ""

#: nova/scheduler/host_manager.py:669
#, python-format
msgid ""
"Received a sync request from an unknown host '%s'. Re-created its "
"InstanceList."
msgstr ""

#: nova/scheduler/client/report.py:73
#, python-format
msgid "Compute_service record updated for %s"
msgstr ""

#: nova/scheduler/filters/utils.py:65
#, python-format
msgid "%(num_values)d values found, of which the minimum value will be used."
msgstr ""

#: nova/virt/block_device.py:222
#, python-format
msgid "preserve multipath_id %s"
msgstr ""

#: nova/virt/block_device.py:427
#, python-format
msgid "Booting with volume %(volume_id)s at %(mountpoint)s"
msgstr "%(mountpoint)s의 %(volume_id)s 볼륨을 사용하여 부팅"

#: nova/virt/driver.py:1385
#, python-format
msgid "Loading compute driver '%s'"
msgstr "계산 드라이버 '%s' 로드 중"

#: nova/virt/firewall.py:173 nova/virt/libvirt/firewall.py:345
msgid "Attempted to unfilter instance which is not filtered"
msgstr "필터링되지 않는 인스턴스를 필터링 해제하려고 했음"

#: nova/virt/firewall.py:443
#, python-format
msgid "instance chain %s disappeared during refresh, skipping"
msgstr ""

#: nova/virt/disk/mount/api.py:121
msgid "Device allocation failed. Will retry in 2 seconds."
msgstr "디바이스 할당에 실패했습니다. 2초 안에 재시도합니다. "

#: nova/virt/disk/mount/loop.py:34
#, python-format
msgid "Loop mount error: %s"
msgstr "루프 마운트 오류: %s"

#: nova/virt/disk/mount/nbd.py:91 nova/virt/disk/mount/nbd.py:104
#, python-format
msgid "NBD mount error: %s"
msgstr "NBD 마운트 오류: %s"

#: nova/virt/disk/vfs/api.py:67
msgid "Unable to import guestfs, falling back to VFSLocalFS"
msgstr ""

#: nova/virt/hyperv/basevolumeutils.py:75
msgid "The ISCSI initiator name can't be found. Choosing the default one"
msgstr "ISCSI 개시자 이름을 찾을 수 없습니다. 기본 이름 선택 중"

#: nova/virt/hyperv/vmops.py:260
msgid "Spawning new instance"
msgstr "새 인스턴스 파생 중"

#: nova/virt/hyperv/vmops.py:378 nova/virt/vmwareapi/vmops.py:664
msgid "Using config drive for instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:392 nova/virt/libvirt/driver.py:2826
#, python-format
msgid "Creating config drive at %(path)s"
msgstr "%(path)s에 구성 드라이브 작성 중"

#: nova/virt/hyperv/vmops.py:442
msgid "Got request to destroy instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:494
msgid "Soft shutdown succeeded."
msgstr ""

#: nova/virt/ironic/driver.py:708
#, python-format
msgid ""
"Config drive for instance %(instance)s on baremetal node %(node)s created."
msgstr ""

#: nova/virt/libvirt/driver.py:522
#, python-format
msgid "Connection event '%(enabled)d' reason '%(reason)s'"
msgstr ""

#: nova/virt/libvirt/driver.py:686
msgid "During wait destroy, instance disappeared."
msgstr "영구 삭제 대기 중에 인스턴스가 사라졌습니다. "

#: nova/virt/libvirt/driver.py:691
msgid "Instance destroyed successfully."
msgstr "인스턴스가 영구 삭제되었습니다. "

#: nova/virt/libvirt/driver.py:701
msgid "Instance may be started again."
msgstr "인스턴스가 다시 시작됩니다."

#: nova/virt/libvirt/driver.py:711
msgid "Going to destroy instance again."
msgstr "인스턴스를 다시 영구 삭제하려 합니다."

#: nova/virt/libvirt/driver.py:1369
msgid "Beginning live snapshot process"
msgstr "라이브 스냅샷 프로세스 시작 중"

#: nova/virt/libvirt/driver.py:1372
msgid "Beginning cold snapshot process"
msgstr "콜드 스냅샷 프로세스 시작 중"

#: nova/virt/libvirt/driver.py:1402
msgid "Snapshot extracted, beginning image upload"
msgstr "스냅샷 추출, 이미지 업로드 시작 중"

#: nova/virt/libvirt/driver.py:1414
msgid "Snapshot image upload complete"
msgstr "스냅샷 이미지 업로드 완료"

#: nova/virt/libvirt/driver.py:1982
msgid "Instance soft rebooted successfully."
msgstr "인스턴스가 소프트 리부트되었습니다. "

#: nova/virt/libvirt/driver.py:2025
msgid "Instance shutdown successfully."
msgstr "인스턴스가 시스템 종료되었습니다. "

#: nova/virt/libvirt/driver.py:2033
msgid "Instance may have been rebooted during soft reboot, so return now."
msgstr ""
"인스턴스가 소프트 리부트 중에 다시 부팅되었을 수 있으므로, 지금 리턴합니다. "

#: nova/virt/libvirt/driver.py:2111
msgid "Instance rebooted successfully."
msgstr "인스턴스가 다시 부트되었습니다. "

#: nova/virt/libvirt/driver.py:2153
msgid "Instance already shutdown."
msgstr ""

#: nova/virt/libvirt/driver.py:2168
#, python-format
msgid "Instance shutdown successfully after %d seconds."
msgstr ""

#: nova/virt/libvirt/driver.py:2197
#, python-format
msgid "Instance failed to shutdown in %d seconds."
msgstr ""

#: nova/virt/libvirt/driver.py:2366
msgid "Instance spawned successfully."
msgstr "인스턴스가 파생되었습니다. "

#: nova/virt/libvirt/driver.py:2382
#, python-format
msgid "data: %(data)r, fpath: %(fpath)r"
msgstr "데이터: %(data)r, fpath: %(fpath)r"

#: nova/virt/libvirt/driver.py:2417
msgid ""
"Instance is configured with a file console, but the backing file is not "
"(yet?) present"
msgstr ""

#: nova/virt/libvirt/driver.py:2428 nova/virt/libvirt/driver.py:2455
#, python-format
msgid "Truncated console log returned, %d bytes ignored"
msgstr "잘린 콘솔 로그가 리턴되었으며, %d 바이트는 무시됨"

#: nova/virt/libvirt/driver.py:2690
msgid "Creating image"
msgstr "이미지 작성 중"

#: nova/virt/libvirt/driver.py:2817
msgid "Using config drive"
msgstr "구성 드라이브 사용 중"

#: nova/virt/libvirt/driver.py:3605
msgid "Configuring timezone for windows instance to localtime"
msgstr ""

#: nova/virt/libvirt/driver.py:4831
#, python-format
msgid ""
"Getting block stats failed, device might have been detached. Instance="
"%(instance_name)s Disk=%(disk)s Code=%(errcode)s Error=%(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4837
#, python-format
msgid ""
"Could not find domain in libvirt for instance %s. Cannot get block stats for "
"device"
msgstr ""
"%s 인스턴스에 대한 libvirt에서 도메인을 찾을 수 없습니다. 디바이스의 블록 통"
"계를 가져올 수 없음"

#: nova/virt/libvirt/driver.py:5158
#, python-format
msgid "Instance launched has CPU info: %s"
msgstr ""

#: nova/virt/libvirt/driver.py:5553
#, python-format
msgid "Error %(ex)s, migration failed"
msgstr ""

#: nova/virt/libvirt/driver.py:5594
#, python-format
msgid ""
"Migration running for %(secs)d secs, memory %(progress)d%% remaining; (bytes "
"processed=%(processed)d, remaining=%(remaining)d, total=%(total)d)"
msgstr ""

#: nova/virt/libvirt/driver.py:5612
msgid "Migration operation has completed"
msgstr ""

#: nova/virt/libvirt/driver.py:6307
msgid "Instance running successfully."
msgstr "인스턴스가 정상적으로 실행 중입니다. "

#: nova/virt/libvirt/driver.py:6662
#, python-format
msgid "Deleting instance files %s"
msgstr ""

#: nova/virt/libvirt/driver.py:6675
#, python-format
msgid "Deletion of %s failed"
msgstr ""

#: nova/virt/libvirt/driver.py:6679
#, python-format
msgid "Deletion of %s complete"
msgstr ""

#: nova/virt/libvirt/firewall.py:115
msgid "Called setup_basic_filtering in nwfilter"
msgstr "nwfilter에서 setup_basic_filtering을 호출했음"

#: nova/virt/libvirt/firewall.py:123
msgid "Ensuring static filters"
msgstr "정적 필터 확인 중"

#: nova/virt/libvirt/host.py:686
#, python-format
msgid ""
"Unable to use bulk domain list APIs, falling back to slow code path: %(ex)s"
msgstr ""

#: nova/virt/libvirt/host.py:736
#, python-format
msgid "Libvirt host capabilities %s"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:398
#, python-format
msgid "Failed to get image info from path %(path)s; error: %(error)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:191
#, python-format
msgid "Writing stored info to %s"
msgstr "%s에 저장된 정보 기록 중"

#: nova/virt/libvirt/imagecache.py:414
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): image verification skipped, no hash stored"
msgstr ""
"(%(base_file)s)의 이미지 %(id)s: 이미지 검증 건너뜀. 해시가 저장되지 않음"

#: nova/virt/libvirt/imagecache.py:423
#, python-format
msgid "%(id)s (%(base_file)s): generating checksum"
msgstr "%(id)s (%(base_file)s): 체크섬 생성 중"

#: nova/virt/libvirt/imagecache.py:452
#, python-format
msgid "Base or swap file too young to remove: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:455
#, python-format
msgid "Removing base or swap file: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:505
#, python-format
msgid "image %(id)s at (%(base_file)s): checking"
msgstr "(%(base_file)s)의 이미지 %(id)s: 검사 중"

#: nova/virt/libvirt/imagecache.py:529
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): in use: on this node %(local)d local, "
"%(remote)d on other nodes sharing this instance storage"
msgstr ""
"(%(base_file)s)의 이미지 %(id)s: 사용 중. 이 노드의 %(local)d 로컬과 다른 노"
"드의 %(remote)d이(가) 이 인스턴스 스노리지를 공유함"

#: nova/virt/libvirt/imagecache.py:612
#, python-format
msgid "Active base files: %s"
msgstr "활성 기본 파일: %s"

#: nova/virt/libvirt/imagecache.py:615
#, python-format
msgid "Corrupt base files: %s"
msgstr "손상된 기본 파일: %s"

#: nova/virt/libvirt/imagecache.py:619
#, python-format
msgid "Removable base files: %s"
msgstr "제거 가능한 기본 파일: %s"

#: nova/virt/libvirt/quobyte.py:50
#, python-format
msgid "Mounted volume: %s"
msgstr ""

#: nova/virt/libvirt/utils.py:259
#, python-format
msgid "tap-ctl check: %s"
msgstr ""

#: nova/virt/libvirt/utils.py:589
msgid "findmnt tool is not installed"
msgstr ""

#: nova/virt/libvirt/volume.py:1555
#, python-format
msgid "Fixing previous mount %s which was not unmounted correctly."
msgstr ""

#: nova/virt/libvirt/volume.py:1576
#, python-format
msgid "Trying to disconnected unmounted volume at %s"
msgstr ""

#: nova/virt/vmwareapi/driver.py:450
#, python-format
msgid "Invalid cluster or resource pool name : %s"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:289
#, python-format
msgid "Moved virtual disk from %(src)s to %(dst)s."
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:307
#, python-format
msgid "Copied virtual disk from %(src)s to %(dst)s."
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:321
#, python-format
msgid "Deleted virtual disk %s."
msgstr ""

#: nova/virt/vmwareapi/imagecache.py:162
#, python-format
msgid "Image %s is no longer used by this node. Pending deletion!"
msgstr ""

#: nova/virt/vmwareapi/imagecache.py:167
#, python-format
msgid "Image %s is no longer used. Deleting!"
msgstr ""

#: nova/virt/vmwareapi/images.py:362
#, python-format
msgid "Downloaded image file data %(image_ref)s"
msgstr ""

#: nova/virt/vmwareapi/images.py:365 nova/virt/vmwareapi/images.py:436
msgid "The imported VM was unregistered"
msgstr ""

#: nova/virt/vmwareapi/images.py:431
#, python-format
msgid "Downloaded OVA image file %(image_ref)s"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1308
msgid "Destroyed the VM"
msgstr "VM을 영구 삭제했음"

#: nova/virt/vmwareapi/vmops.py:768
msgid "Created linked-clone VM from snapshot"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1308 nova/virt/xenapi/vmops.py:1677
#, python-format
msgid "Found %(instance_count)d hung reboots older than %(timeout)d seconds"
msgstr "%(timeout)d 초 이상 %(instance_count)d 정지된 재부트 발견"

#: nova/virt/vmwareapi/vmops.py:1312 nova/virt/xenapi/vmops.py:1681
msgid "Automatically hard rebooting"
msgstr "자동으로 하드 재부팅 중"

#: nova/virt/vmwareapi/volumeops.py:443
#, python-format
msgid ""
"The volume's backing has been relocated to %s. Need to consolidate backing "
"disk file."
msgstr ""

#: nova/virt/xenapi/agent.py:396
msgid ""
"XenServer tools installed in this image are capable of network injection.  "
"Networking files will not bemanipulated"
msgstr ""
"이 이미지에 설치된 XenServer 도구는 네트워크 삽입이 가능합니다. 네트워킹 파일"
"이 수정되지 않습니다. "

#: nova/virt/xenapi/agent.py:404
msgid ""
"XenServer tools are present in this image but are not capable of network "
"injection"
msgstr "XenServer 도구가 이 이미지에 존재하지만 네트워크 삽입을 사용할 수 없음"

#: nova/virt/xenapi/agent.py:408
msgid "XenServer tools are not installed in this image"
msgstr "XenServer 도구가 이 이미지에 설치되지 않았음"

#: nova/virt/xenapi/host.py:75
#, python-format
msgid ""
"Instance %(name)s running on %(host)s could not be found in the database: "
"assuming it is a worker VM and skip ping migration to a new host"
msgstr ""
"%(host)s 호스트에서 실행 중인 %(name)s 인스턴스를 데이터베이스에서 찾을 수 없"
"음. 이를 작업자 VM이라고 가정하고 새 호스트로의 ping 마이그레이션을 건너뛰는 "
"중"

#: nova/virt/xenapi/vm_utils.py:395
#, python-format
msgid "VBD %s already detached"
msgstr "VBD %s이(가) 이미 분리되었음"

#: nova/virt/xenapi/vm_utils.py:398
#, python-format
msgid ""
"VBD %(vbd_ref)s uplug failed with \"%(err)s\", attempt %(num_attempt)d/"
"%(max_attempts)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:685
#, python-format
msgid "Deleted %s snapshots."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1328
#, python-format
msgid ""
"Image creation data, cacheable: %(cache)s, downloaded: %(downloaded)s "
"duration: %(duration).2f secs for image %(image_id)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2176
#, python-format
msgid "Disconnecting stale VDI %s from compute domU"
msgstr "계산 domU에서 이전 VDI %s 연결을 끊는 중"

#: nova/virt/xenapi/vm_utils.py:2469
msgid "Manipulating interface files directly"
msgstr "인터페이스 파일을 직접 조작 중"

#: nova/virt/xenapi/vm_utils.py:2478
#, python-format
msgid "Failed to mount filesystem (expected for non-linux instances): %s"
msgstr "파일 시스템 마운트 실패(비linux 인스턴스의 경우에 예상됨): %s"

#: nova/virt/xenapi/vmops.py:1263
msgid "Starting halted instance found during reboot"
msgstr "다시 부팅 중에 정지된 인스턴스 시작이 발견됨"

#: nova/virt/xenapi/vmops.py:1467
msgid "Destroying VM"
msgstr "VM 영구 삭제 중"

#: nova/virt/xenapi/volumeops.py:64
#, python-format
msgid "Connected volume (vdi_uuid): %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:127
#, python-format
msgid "Dev %(dev_number)s attached to instance %(instance_name)s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:149
#, python-format
msgid "Mountpoint %(mountpoint)s detached from instance %(instance_name)s"
msgstr "%(mountpoint)s 마운트 지점이 %(instance_name)s 인스턴스에서 분리됨"

#: nova/vnc/xvp_proxy.py:94
#, python-format
msgid "Error in handshake format: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:100
#, python-format
msgid "Error in handshake: %s"
msgstr "핸드쉐이크의 오류: %s"

#: nova/vnc/xvp_proxy.py:115
#, python-format
msgid "Invalid request: %s"
msgstr "올바르지 않은 요청: %s"

#: nova/vnc/xvp_proxy.py:135
#, python-format
msgid "Request: %s"
msgstr "요청: %s"

#: nova/vnc/xvp_proxy.py:138
#, python-format
msgid "Request made with missing token: %s"
msgstr "요청이 누락된 토큰과 함께 작성됨: %s"

#: nova/vnc/xvp_proxy.py:148
#, python-format
msgid "Request made with invalid token: %s"
msgstr "요청이 올바르지 않은 토큰과 함께 작성됨: %s"

#: nova/vnc/xvp_proxy.py:155
#, python-format
msgid "Unexpected error: %s"
msgstr "예기치 않은 오류: %s"

#: nova/vnc/xvp_proxy.py:175
#, python-format
msgid "Starting nova-xvpvncproxy node (version %s)"
msgstr "nova-xvpvncproxy 노드(버전 %s) 시작 중"

#: nova/volume/encryptors/luks.py:110
#, python-format
msgid "%s is not a valid LUKS device; formatting device for first use"
msgstr ""
